import type { Course } from "./types";

export const COURSES: Course[] = [
  {
    id: "1",
    title: "3D Geometry Fundamentals",
    description:
      "Master the basics of three-dimensional shapes, surfaces, and spatial relationships",
    level: "Beginner",
    duration: "6 weeks",
    lessons: 28,
    rating: 4.8,
    enrolled: 1240,
    colorClass: "bg-gradient-to-br from-blue-400 to-blue-600",
  },
  {
    id: "2",
    title: "Spatial Reasoning & Problem Solving",
    description:
      "Develop advanced spatial reasoning skills through interactive challenges",
    level: "Intermediate",
    duration: "8 weeks",
    lessons: 32,
    rating: 4.9,
    enrolled: 987,
    colorClass: "bg-gradient-to-br from-purple-400 to-purple-600",
  },
  {
    id: "3",
    title: "Vector Mathematics",
    description: "Deep dive into vectors, transformations, and their spatial applications",
    level: "Intermediate",
    duration: "7 weeks",
    lessons: 24,
    rating: 4.7,
    enrolled: 856,
    colorClass: "bg-gradient-to-br from-green-400 to-green-600",
  },
  {
    id: "4",
    title: "Topological Thinking",
    description: "Explore the fascinating world of topology and spatial transformations",
    level: "Advanced",
    duration: "10 weeks",
    lessons: 18,
    rating: 4.9,
    enrolled: 432,
    colorClass: "bg-gradient-to-br from-orange-400 to-orange-600",
  },
  {
    id: "5",
    title: "CAD & 3D Modeling Basics",
    description: "Learn computer-aided design and create your first 3D models",
    level: "Beginner",
    duration: "8 weeks",
    lessons: 32,
    rating: 4.6,
    enrolled: 1567,
    colorClass: "bg-gradient-to-br from-pink-400 to-pink-600",
  },
  {
    id: "6",
    title: "Spatial Data Visualization",
    description:
      "Visualize complex spatial data and create compelling 3D representations",
    level: "Advanced",
    duration: "9 weeks",
    lessons: 26,
    rating: 4.8,
    enrolled: 674,
    colorClass: "bg-gradient-to-br from-cyan-400 to-cyan-600",
  },
  {
    id: "7",
    title: "Architectural Spatial Design",
    description: "Apply spatial concepts to architectural design and planning",
    level: "Intermediate",
    duration: "12 weeks",
    lessons: 36,
    rating: 4.7,
    enrolled: 523,
    colorClass: "bg-gradient-to-br from-indigo-400 to-indigo-600",
  },
  {
    id: "8",
    title: "Virtual Reality Environments",
    description: "Design and develop immersive VR spatial experiences",
    level: "Advanced",
    duration: "10 weeks",
    lessons: 30,
    rating: 4.9,
    enrolled: 789,
    colorClass: "bg-gradient-to-br from-rose-400 to-rose-600",
  },
  {
    id: "9",
    title: "Coordinate Systems & Projections",
    description: "Understand different coordinate systems and spatial projections",
    level: "Beginner",
    duration: "5 weeks",
    lessons: 20,
    rating: 4.5,
    enrolled: 1123,
    colorClass: "bg-gradient-to-br from-amber-400 to-amber-600",
  },
];