-- AlterTable
ALTER TABLE "User" ADD COLUMN     "goalDaily" INTEGER NOT NULL DEFAULT 30,
ADD COLUMN     "goalStreak" INTEGER NOT NULL DEFAULT 14,
ADD COLUMN     "goalWeekly" INTEGER NOT NULL DEFAULT 5;
